version: "2"

services:
  voting-app:
    build: ./voting-app
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker

  db:
    image: postgres:9.4

  result-app:
    build: ./result-app
    command: nodemon --debug server.js
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
      - "5858:5858"
