apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: akshataazurecicd.azurecr.io/worker:20
        name: worker
      ports:
        - containerPort: 80
          name: worker
      imagePullSecrets:
      - name: secret
